### ISSUE TITLE
Add a sample as an executable code

### ISSUE THREAD

**Issue by daniel-a111** [avishsa/MathChallenges#1]
Please add instruction and an example of algorithm execution.

**Comment by avishsa** [comment]
done

**Comment by avishsa** [comment]
I'm closing the issue

**Comment by daniel-a111** [comment]
Hi @avishsa,

Usually we use a "package manager" to handle java compilation and execution, in an environment independent.

Take a look at one of the common package managers for Java that is called Maven (https://maven.apache.org/).

Installation & execution instructions then should be IDE (Eclipse) independent. 
You can use the following simple repository: https://github.com/jabedhasan21/java-hello-world-with-maven, that is examine a simple Maven application.

Thanks :)
